
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from hooks.py and the example nodes in
# `src/pipelines/`
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/02_configuration.html#parameters
example_test_data_ratio: 0.2
example_num_train_iter: 10000
example_learning_rate: 0.01

random_seed: 12345

wigi_data_setpath: "~/Personal/datathon2020/datathon_2020/data/01_raw/wgidataset_stata"

wigi_linear_model_formula: "excess_deaths_per_100k ~ govt_trust_index"

wigi_linear_model_regressor_no: 1

hospital_beds_param: "hospital_beds_per_1000"
specialist_doctors_param: "specialist_doctors_pct"
health_workers_param: "health_workers_pct"
physicians_param: "physicians_pct"
handwashing_param: "handwashing_pct"
glbl_population_param: "population_total"